# Generated by Django 4.0.4 on 2022-05-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0002_image_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='api/images/'),
        ),
    ]
